studentsdb/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .settings import MEDIA_ROOT, DEBUG

from students.views.students import StudentUpdateView, StudentCreateView, StudentDeleteView, StudentList
from students.views.groups import GroupList, GroupAddView, GroupUpdateView,GroupDeleteView 
from students.views.exams import ExamList, ExamAddView, ExamEditView, ExamDeleteView
from students.views.teachers import TeacherList, TeacherAddView, TeacherUpdateView, TeacherDeleteView
from students.views.contact_teacher import ContactTeacher
from students.views.contact_group import ContactGroup
from students.views.journal import JournalView
from django.views.generic.base import RedirectView, TemplateView

from django.contrib.auth import views as auth_views

from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',
    # User Related urls
    url(r'^users/logout/$', auth_views.logout, kwargs={'next_page':'home'}, name='auth_logout'),

    url(r'^register/complete/$', RedirectView.as_view(pattern_name='home'),name='registration_complete'),
    url(r'^users/profile/$', login_required(TemplateView.as_view(template_name='registration/profile.html')), name='profile'),
    
    url(r'^users/', include('registration.backends.simple.urls', namespace='users')),

    # Examples:
    url(r'^$', StudentList.as_view(), name='home'),
    # url(r'^blog/', include('blog.urls')),
    #Student urls
    url(r'^students/add/$', StudentCreateView.as_view(),name='students_add'),

    url(r'^students/(?P<pk>\d+)/edit/$', StudentUpdateView.as_view(),name='students_edit'),

    url(r'^students/(?P<sid>\d+)/delete/$', 'students.views.students.students_delete',name='students_delete'),
    
    url(r'^students/delete_several/$','students.views.students.students_delete_several',name='students_delete_several'),

    url(r'^students/stats/$','students.views.stats.presense_stats',name='students_stats'),


    url(r'^admin/', include(admin.site.urls)),

    #Group urls
    url(r'^groups/$', GroupList.as_view(), name='groups_list'),

    url(r'^groups/add/$', login_required(GroupAddView.as_view()), name='groups_add'),

    url(r'^groups/(?P<pk>\d+)/edit/$', GroupUpdateView.as_view(), name='groups_edit'),

    url(r'^groups/(?P<pk>\d+)/delete/$', GroupDeleteView.as_view() ,name='groups_delete'),

    #Journal  urls
     url(r'^journal/(?P<pk>\d+)?/?$', JournalView.as_view(), name='journal'),
     
    #Exams urls
    url(r'^exams/$', ExamList.as_view(), name='exams_list'),

    url(r'^exams/add/$', ExamAddView.as_view(),name='exams_add'),

    url(r'^exams/(?P<pk>\d+)/edit/$', ExamEditView.as_view(),name='exams_edit'),

    url(r'^exams/(?P<pk>\d+)/delete/$', ExamDeleteView.as_view() ,name='exams_delete'),

    #teachers urls
    url(r'^teachers/$', TeacherList.as_view(), name='teachers_list'),

    url(r'^teachers/add/$', TeacherAddView.as_view() ,name='teachers_add'),

    url(r'^teachers/(?P<pk>\d+)/edit/$', TeacherUpdateView.as_view() ,name='teachers_edit'),

    url(r'^teachers/(?P<pk>\d+)/delete/$', TeacherDeleteView.as_view() ,name='teachers_delete'),
    
    #Contact Admin Form 
    url(r'^contact-teacher/$', ContactTeacher.as_view(), name='contact_teacher'),
    url(r'^contact-group/$', ContactGroup.as_view(), name='contact_group'),
    
)

urlpatterns += staticfiles_urlpatterns()

if DEBUG:
# serve files from media folder 
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': MEDIA_ROOT}))

students/models/exams.py
# -*- coding: utf-8 -*-
from django.db import models


# Create your models here.
class Exam(models.Model):
    """Exam model"""

    class Meta(object):
        verbose_name=u"Екзамен"
        verbose_name_plural= "Екзамени" 


    name = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=u"Назва")

    date = models.DateTimeField(
    blank=False,
    verbose_name=u"Дата і час проведення",
    null=True)

    exam_teacher = models.ForeignKey('Teacher',
    max_length=256,
    blank=True,
    null=True,
    verbose_name = "Викладач")

    groups = models.ForeignKey(
    'Group',
    blank=False,
    verbose_name='Група',
    null=True)

    notes = models.TextField(
    blank=True,
    verbose_name=u"Нотатки")

    def __unicode__(self):
        if self.exam_teacher:
            return u"%s (%s %s)" % (self.name, self.exam_teacher.first_name, self.exam_teacher.last_name)
        else:
            return u"%s" % (self.name)

students/models/groups.py
# -*- coding: utf-8 -*-
from django.db import models

class Group(models.Model):
    """Group model"""

    class Meta(object):
        verbose_name=u"Група"
        verbose_name_plural= "Групи"



    title = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=u"Назва")

    leader=models.OneToOneField('Student',
    verbose_name="Староста",
    blank=True,
    null=True, 
    on_delete=models.SET_NULL) 


    notes = models.TextField(
    blank=True,
    verbose_name=u"Нотатки")

    def __unicode__(self):
        if self.leader:
            return u"%s (%s %s)" % (self.title, self.leader.first_name, self.leader.last_name)
        else:
            return u"%s" % (self.title)

students/models/students.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Student(models.Model):
    """Student model"""

    class Meta(object):
        verbose_name=u"Студент"
        verbose_name_plural= "Студенти"
        permissions = (
            ("contact_teacher", "Student can contact teacher"),
            ("group_leader", "Permission for managing the journal")
        )
         


    first_name = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=u"Ім'я")


    last_name = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=u"Прізвище")


    middle_name = models.CharField(
    max_length=256,
    blank=True, 
    verbose_name=u"По-батькові",
    default='')


    birthday = models.DateField(
    blank=False,
    verbose_name=u"Дата народження",
    null=True)


    photo = models.ImageField(
    blank=True,
    verbose_name=u"Фото",
    null=True)


    ticket = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=u"Білет")

    student_group = models.ForeignKey('Group',
    verbose_name="Група",
    blank=False,
    null=True,
    on_delete=models.PROTECT)
    
    notes = models.TextField(
    blank=True,
    verbose_name=u"Нотатки")

    user = models.OneToOneField(User,
    verbose_name="Користувач",
    blank=True,
    null=True)

    def __unicode__(self):
        return u"%s %s" % (self.first_name, self.last_name)


     

students/models/teachers.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User

class Teacher(models.Model):
    """Group model"""

    class Meta(object):
        verbose_name=u"Викладач"
        verbose_name_plural= "Викладачі"
        permissions = (
            ("contact_student", "Teacher can contact student"),
        )



    first_name = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=u"Ім'я")


    last_name = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=u"Прізвище")


    middle_name = models.CharField(
    max_length=256,
    blank=True, 
    verbose_name=u"По-батькові",
    default='')


    birthday = models.DateField(
    blank=False,
    verbose_name=u"Дата народження",
    null=True)


    photo = models.ImageField(
    blank=True,
    verbose_name=u"Фото",
    null=True)

    notes = models.TextField(
    blank = True,
    verbose_name = u"Нотатки")

    user = models.OneToOneField(User,
    blank=True,
    null=True,
    verbose_name='Користувач')




    def __unicode__(self):
        return u"%s %s" % (self.first_name, self.last_name)

students/views/contact_admin.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django import forms
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.core.urlresolvers import reverse_lazy

from django.contrib import messages
from django.contrib.messages import get_messages


from studentsdb.settings import ADMIN_EMAIL

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from django.views.generic.edit import FormView



class ContactForm(forms.Form):

	def __init__(self, *args, **kwargs):
		#call original initializator
		super(ContactForm, self).__init__(*args, **kwargs)

		#this helper object allows us to customize form 
		self.helper = FormHelper()

		# form tag attributes
		self.helper.form_class = 'form-horizontal'
		self.helper.form_mehtod = 'post'
		self.helper.form_action = reverse('contact_admin')

		#twitter bootstrap styles

		self.helper.help_text_inline = True
		self.helper.html5_required = True
		self.helper.label_class = 'col-sm-2 control-label'
		self.helper.field_class = 'col-sm-10'

		#form buttons 
		self.helper.add_input(Submit('send_button',u'Надіслати'))
		
	from_email = forms.EmailField(label=u"Ваша емейл адреса")

	subject = forms.CharField(label=u"Заголовок листа", max_length = 128)

	message = forms.CharField(label=u"Текст повідомлення", max_length=2560, widget = forms.Textarea)


class ContactView(FormView):
	
	template_name="contact_admin/form.html"
	form_class = ContactForm
	# success_message="Повідомлення успішно відправлено."
#	success_url=reverse_lazy('contact_admin')
        
	def get_success_url(self):
    	    return reverse('contact_admin')

	def form_valid(self,form):
	    subject = form.cleaned_data['subject']
     	    message = form.cleaned_data['message']
    	    from_email = form.cleaned_data['from_email']

    	    send_mail(subject, message + "\n\n Message was sent from: " + from_email, 'Student DB', [ADMIN_EMAIL])
            storage = get_messages(self.request)
            for message in storage:
               pass
            messages.add_message(self.request, messages.INFO, "Повідомлення успішно відправлено.")
    	    return super(ContactView, self).form_valid(form)

	

		
# def contact_admin(request):
#     if request.method == 'POST':
#     	form = ContactForm(request.POST)

#     	# check wether user data is valid
#     	if form.is_valid():
#     		subject = form.cleaned_data['subject']
#     		message = form.cleaned_data['message']
#     		from_email = form.cleaned_data['from_email']
# 	    	try:
# 	    		send_mail(subject, message + "\n\n Message was sent from: " + from_email, 'Student DB', [ADMIN_EMAIL])
# 	    	except Exception:
# 	    		message = u"Під час відправки листа виникла помилка. Спробуйте пізніше."
# 	    	else:
# 	    		message = u"Повідомлення успішно надіслано"
	    	
# 	    	return HttpResponseRedirect(u'%s?status_message=%s' % (reverse(contact_admin), message))
    
#     else:
#     	form = ContactForm()

#     return render(request, 'contact_admin/form.html',{'form':form})

students/views/contact_group.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django import forms
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.core.urlresolvers import reverse_lazy

from django.contrib import messages
from django.contrib.messages import get_messages


from studentsdb.settings import ADMIN_EMAIL

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from django.views.generic.edit import FormView

from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import permission_required

from django.contrib.auth.models import AbstractUser, User


class ContactForm(forms.Form):

	def __init__(self, *args, **kwargs):
		#call original initializator
		super(ContactForm, self).__init__(*args, **kwargs)

		import pdb; pdb.set_trace;
		#this helper object allows us to customize form 
		self.helper = FormHelper()

		# form tag attributes
		self.helper.form_class = 'form-horizontal'
		self.helper.form_mehtod = 'post'
		self.helper.form_action = reverse('contact_group')

		#twitter bootstrap styles

		self.helper.help_text_inline = True
		self.helper.html5_required = True
		self.helper.label_class = 'col-sm-2 control-label'
		self.helper.field_class = 'col-sm-10'

		#form buttons 
		self.helper.add_input(Submit('send_button',u'Надіслати'))
	
	from .groups import Group
	group = forms.ModelChoiceField(queryset = Group.objects.all(), empty_label="Обрати групу",label=u"Група")

	subject = forms.CharField(label=u"Заголовок листа", max_length = 128)

	message = forms.CharField(label=u"Текст повідомлення", max_length=2560, widget = forms.Textarea)


class ContactGroup(FormView):
	
	template_name="students/contact_form.html"
	form_class = ContactForm

	def get_context_data(self, *args, **kwargs):

	    context = super(ContactGroup, self).get_context_data(*args, **kwargs)
	    context["name"] = "Групою"

	    return context
	# success_message="Повідомлення успішно відправлено."
#	success_url=reverse_lazy('contact_admin')
       
	def get_success_url(self):
    	    return reverse('contact_group')

	def form_valid(self,form):
	    # import pdb; pdb.set_trace();
	    # if leader has no email attached
	    try:
	    	group = form.cleaned_data['group']
	    	group_email = group.leader.user.email
	    except:
	    	return HttpResponseRedirect(u'%s?status_message=Помилка на сервері'%reverse('contact_group'))
	    
	    subject = form.cleaned_data['subject']
    	    message = form.cleaned_data['message']
    	    

    	    send_mail(subject, message, 'Student DB', [group_email])
    	    # email_user(subject, message)
    	    storage = get_messages(self.request)
    	    for message in storage:
        	pass
    	    messages.add_message(self.request, messages.INFO, "Повідомлення успішно відправлено.")
    	    return super(ContactGroup, self).form_valid(form)

	

students/views/contact_teacher.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django import forms
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.core.urlresolvers import reverse_lazy

from django.contrib import messages
from django.contrib.messages import get_messages


from studentsdb.settings import ADMIN_EMAIL

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from django.views.generic.edit import FormView

from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import permission_required

from django.contrib.auth.models import AbstractUser, User


class ContactForm(forms.Form):

	def __init__(self, *args, **kwargs):
		#call original initializator
		super(ContactForm, self).__init__(*args, **kwargs)

		import pdb; pdb.set_trace;
		#this helper object allows us to customize form 
		self.helper = FormHelper()

		# form tag attributes
		self.helper.form_class = 'form-horizontal'
		self.helper.form_mehtod = 'post'
		self.helper.form_action = reverse('contact_teacher')

		#twitter bootstrap styles

		self.helper.help_text_inline = True
		self.helper.html5_required = True
		self.helper.label_class = 'col-sm-2 control-label'
		self.helper.field_class = 'col-sm-10'

		#form buttons 
		self.helper.add_input(Submit('send_button',u'Надіслати'))
	
	from .teachers import Teacher
	teacher = forms.ModelChoiceField(queryset = Teacher.objects.all(), empty_label="Обрати викладача",label=u"Викладач")

	subject = forms.CharField(label=u"Заголовок листа", max_length = 128)

	message = forms.CharField(label=u"Текст повідомлення", max_length=2560, widget = forms.Textarea)


class ContactTeacher(FormView):
	
	template_name="students/contact_form.html"
	form_class = ContactForm
	# success_message="Повідомлення успішно відправлено."
#	success_url=reverse_lazy('contact_admin')
	def get_context_data(self, *args, **kwargs):

	    context = super(ContactTeacher, self).get_context_data(*args, **kwargs)
	    context["name"] = "Викладачем"

	    return context
       
	def get_success_url(self):
    	    return reverse('contact_teacher')

	def form_valid(self,form):
	    # import pdb; pdb.set_trace();
	    try:
		teacher = form.cleaned_data['teacher']
		teacher_email = teacher.user.email
    	    except:
		return HttpResponseRedirect(u'%s?status_message=Помилка на сервері'%reverse('contact_teacher'))
	    subject = form.cleaned_data['subject']
     	    message = form.cleaned_data['message']
    	    from_email = form.cleaned_data['teacher']

    	    send_mail(subject, message, 'Student DB', [teacher_email])
    	    # email_user(subject, message)
    	    storage = get_messages(self.request)
    	    for message in storage:
    		pass
    	    messages.add_message(self.request, messages.INFO, "Повідомлення успішно відправлено.")
    	    return super(ContactTeacher, self).form_valid(form)

	

		
# def contact_admin(request):
#     if request.method == 'POST':
#     	form = ContactForm(request.POST)

#     	# check wether user data is valid
#     	if form.is_valid():
#     		subject = form.cleaned_data['subject']
#     		message = form.cleaned_data['message']
#     		from_email = form.cleaned_data['from_email']
# 	    	try:
# 	    		send_mail(subject, message + "\n\n Message was sent from: " + from_email, 'Student DB', [ADMIN_EMAIL])
# 	    	except Exception:
# 	    		message = u"Під час відправки листа виникла помилка. Спробуйте пізніше."
# 	    	else:
# 	    		message = u"Повідомлення успішно надіслано"
	    	
# 	    	return HttpResponseRedirect(u'%s?status_message=%s' % (reverse(contact_admin), message))
    
#     else:
#     	form = ContactForm()

#     return render(request, 'contact_admin/form.html',{'form':form})

students/templates/students/exams_list.html
{% extends "students/base.html" %}

{% block meta_title %}Список екзаменів {% endblock meta_title %}

{% block title %}Список екзаменів{% endblock title %}

{% load static from staticfiles %}

{%block content%}
{% if perms.students.add_student %}
<a href="{% url "exams_add" %}" class="btn btn-primary">Додати Екзамен</a>
{% endif %}
					{% if exams %}
					<!-- Start table-->
					<table class="table table-modified"> 
					{% with order_by=request.GET.order_by reverse=request.GET.reverse %}
						<thead>
							<tr>
                  <th>
                      <a href="{% url "exams_list"%}?order_by=id{% if order_by == 'id' and reverse != '1' %}&amp;reverse=1 {% endif %}">#{% if order_by == 'id'  and reverse != '1' %}&uarr;{%  elif order_by == 'id'  and reverse == '1'  %} &darr; {%endif%}
                      </a>
                   </th>
								<th>
								<a href="{% url "exams_list" %}?order_by=name{% if order_by == 'name' and reverse != '1' %}&amp;reverse=1 {% endif %}">Назва{% if order_by == 'name'  and reverse != '1' %}&uarr;{%  elif order_by == 'name'  and reverse == '1'  %} &darr; {%endif%}
								</a>
								</th>
								<th>
								<a href="{% url "exams_list" %}?order_by=date{% if order_by == 'date' and reverse != '1' %}&amp;reverse=1 {% endif %}">Дата і час проведення{% if order_by == 'date'  and reverse != '1' %}&uarr;{%  elif order_by == 'date'  and reverse == '1'  %} &darr; {%endif%}
								</a>
								</th>
								
								<th>
								<a href="{% url "exams_list" %}?order_by=exam_teacher{% if order_by == 'exam_teacher' and reverse != '1' %}&amp;reverse=1 {% endif %}">Викладач{% if order_by == 'exam_teacher'  and reverse != '1' %}&uarr;{%  elif order_by == 'exam_teacher'  and reverse == '1'  %} &darr; {%endif%}
								</a>
								</th>

								<th>
								<a href="{% url "exams_list" %}?order_by=groups{% if order_by == 'groups' and reverse != '1' %}&amp;reverse=1 {% endif %}">Група{% if order_by == 'groups'  and reverse != '1' %}&uarr;{%  elif order_by == 'groups'  and reverse == '1'  %} &darr; {%endif%}
								</a>
								</th>
								
								{% if perms.students.add_student %}<th>Дії</th>{% endif %}
							</tr>
						</thead>
						<tbody>
							{% for exam in exams %}
							<tr>
								<td>{{exam.id}}</td>
								<td>
								{% if  perms.students.add_student %}
								<a href="{% url "exams_edit" exam.id %}" class="edit-form-link">{{exam.name}}</a>
								{% else %} {{exam.name}} {% endif %}
								</td>
                <td>{{exam.date|date:"d.m.Y, H:i"}}</td>
                <td> {% if exam.exam_teacher %}{% if  perms.students.add_student %}<a href="{% url "teachers_edit" exam.exam_teacher.id %}" class="edit-form-link">{{exam.exam_teacher}} </a>{% else %} {{exam.exam_teacher}} {% endif %} {% else %}Немає викладача{% endif %}</td>
								<td>
								{% if perm.auth.add_user %}
								<a href="{% url "groups_edit" exam.groups.id %}" class="edit-form-link">{{exam.groups}}</a>
								{% else %} {{exam.groups}} {% endif %}
								</td>
								{% if  perms.students.add_student %}
								<td>
									<div class="btn-group">
									  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
									    Дії 
									    <span class="caret"></span>
									  </button>
										  <ul class="dropdown-menu" role="menu">
											    <li><a href="{% url "exams_edit" exam.id %}">Редагувати</a></li>
											    <li><a href="{% url "exams_delete" exam.id %}">Видалити</a></li>
											
										  </ul>
									</div>
								</td>
								{% endif %}
							</tr> 
							{% endfor %}
						</tbody>
					</table>
					 {% endwith %}
					<!-- End table-->
					{% else%}
						<p>Поки немає екзаменів у базі</p>
					{% endif%}
					<!-- Start pagination-->
					<div>
						{% with object_list=exams %}
                {% include "students/pagination.html" %}
          	{% endwith %}
          	{% block pagination %}{% endblock pagination %}
					</div>
					<!-- End pagination-->

{%endblock content%}

students/templates/students/exams_universal.html
{% extends "students/base.html" %}

{% block meta_title %}Екзамен {% endblock meta_title %}

{% block title %}  {{name}} Екзамен {% endblock title %}

{% load static from staticfiles %}
{% load crispy_forms_tags %}

{% block status_message %}
{% if form.errors%}
	<div class="alert alert-warning" role="alert">Будь - ласка, виправете наступні помилки  </div> 
{% endif %}
{% endblock %}

{%block content%}


{% crispy form %}

{%endblock content%}

students/templates/students/groups_confirm_delete.html
{% extends "students/base.html" %}

{% block meta_title %}Видалити групу {% endblock meta_title %}

{% block title %}Видалити групу{% endblock title %}

{% load static from staticfiles %}

{%block content%}

<form action="{% url "groups_delete" object.id %}" method="post">
	{% csrf_token %}

	<p> Ви дійсно хочете видалати групу "{{object}}"? </p>
	<input type="submit" value="Так" name="delete_button" class="btn btn-danger"/>
	<input type="submit" value="Ні" name="cancel_button" class="btn btn-primary"/>


	
</form>


{%endblock content%}

students/templates/students/teachers_list.html
{% extends "students/base.html" %}

{% block meta_title %}Список викаладачів {% endblock meta_title %}

{% block title %}Список викладачів{% endblock title %}

{% load static from staticfiles %}

{%block content%}
{% if  perms.students.add_student %}
<a href="{% url "teachers_add" %}" class="btn btn-primary">Додати Викладача</a>
{% endif %}
					{% if teachers %}
					<!-- Start table-->
					<table class="table"> 
					{% with order_by=request.GET.order_by reverse=request.GET.reverse %}
						<thead>
							<tr>
								<th>
								<a href="{% url "teachers_list" %}?order_by=id{% if order_by == 'id'  and reverse != '1' %}&amp;reverse=1{% endif %}">#
								{% if order_by == 'id'  and reverse != '1' %}&uarr;{%  elif order_by == 'id'  and reverse == '1'  %} &darr; {%endif%}
								</a>
								</th>

								<th>Фото</th>

								<th>
								<a href="{% url "teachers_list" %}?order_by=last_name{% if order_by == 'last_name'  and reverse != '1' %}&amp;reverse=1{% endif %}">Прізвище
								{% if order_by == 'last_name'  and reverse != '1' %}&uarr;{%  elif order_by == 'last_name'  and reverse == '1'  %} &darr; {%endif%}
								</a>
								</th>
								
								<th>
								<a href="{% url "teachers_list" %}?order_by=first_name{% if order_by == 'first_name'  and reverse != '1' %}&amp;reverse=1{% endif %}">Імя
								{% if order_by == 'first_name'  and reverse != '1' %}&uarr;{%  elif order_by == 'first_name'  and reverse == '1'  %} &darr; {%endif%}
								</a>
								</th>

								<th>
								<a href="{% url "teachers_list" %}?order_by=subject{% if order_by == 'subject'  and reverse != '1' %}&amp;reverse=1{% endif %}">Предмет
								{% if order_by == 'subject'  and reverse != '1' %}&uarr;{%  elif order_by == 'subject'  and reverse == '1'  %} &darr; {%endif%}
								</a>
								</th>
								
								{% if  perms.students.add_student %}<th>Дії</th>{% endif %}
							</tr>
						</thead>
						<tbody>
							{% for teacher in teachers %}
							<tr>
								<td>{{teacher.id}}</td>
								<td>
								{%if teacher.photo %}
								<img class="img-circle" src="{{ teacher.photo.url }}" height="30" width="30">
								{%else%}
								<img class="img-circle" src="{% static "img/default-user.png" %}" height="30" width="30">
								{%endif%}
								</td>
								<td>{% if  perms.students.add_student %}<a href="{% url "teachers_edit" teacher.id %}" class="edit-form-link">{{teacher.last_name}}</a>{% else %}{{teacher.last_name}}{% endif %}</td>
								<td>{% if  perms.students.add_student %}<a href="{% url "teachers_edit" teacher.id %}" class="edit-form-link">{{teacher.first_name}}</a>{% else %}{{teacher.first_name}}{% endif %}</td>
								<td>
								
                  <ul class="teacher_exam-list">
                  	{% for exam in teacher.exam_set.all %}
                    <li>{{ exam.name }}</li>
                    {% endfor %}
                  </ul>
                    
                </td>
								{% if  perms.students.add_student %}
								<td>
									<div class="btn-group">
									  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
									    Дії 
									    <span class="caret"></span>
									  </button>
										  <ul class="dropdown-menu" role="menu">
											    <li><a href="{% url "teachers_edit" teacher.id %}">Редагувати</a></li>
											    <li><a href="{% url "teachers_delete" teacher.id %}">Видалити</a></li>
											
										  </ul>
									</div>
								</td>
								{% endif %}
							</tr> 
							{% endfor %}
						</tbody>
					</table>
					 {% endwith %}
					<!-- End table-->
					{% else%}
						<p>Поки немає викладачів у базі</p>
					{% endif%}
					<!-- Start pagination-->
					<div>
					{% with object_list=teachers %}
                  {% include "students/pagination.html" %}
          {% endwith %}
					</div>
					<!-- End pagination-->

{%endblock content%}